# Prometheus Configuration
# Scrapes metrics from Recognition API and related services

global:
  # Scrape every 15 seconds
  scrape_interval: 15s
  
  # Evaluate rules every 15 seconds
  evaluation_interval: 15s
  
  # Global labels attached to all time series
  external_labels:
    monitor: 'recognition-api-monitor'
    environment: 'development'

# Alert rules file
rule_files:
  - '/etc/prometheus/alert-rules.yml'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# Scrape configurations
scrape_configs:
  # Main API metrics endpoint
  - job_name: 'recognition-api'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    
  # Appwrite database metrics (if exposed)
  - job_name: 'appwrite-db'
    static_configs:
      - targets: ['localhost:5432']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        
  # S3/Storage metrics (if applicable)
  - job_name: 's3-storage'
    static_configs:
      - targets: ['localhost:9000']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    
  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

# Remote storage (optional, for long-term retention)
# remote_write:
#   - url: http://localhost:9009/api/v1/push
#     queue_config:
#       max_shards: 1

# Service discovery (optional, for dynamic targets)
# consul_sd_configs:
#   - server: 'localhost:8500'
#     datacenter: 'dc1'
